project:
  type: website

execute:
  freeze: auto

website:
  page-navigation: true
  title: "Generative AI in Education"
  description: "Homepage for Generatibve AI project at HdM Stuttgart, SS 2024."
  site-url: "https://generative-ai-education.github.io/website/"
  repo-url: https://github.com/generative-ai-education/website
  repo-actions: [edit, issue]
  open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay  
  page-footer:
    left: |
      © [Jan Kirenz](https://www.kirenz.com/), 2024
    center:
      - text: "Schedule"
        href: index.qmd
      - text: "Syllabus"
        href: course-syllabus.qmd  
    right:
      - icon: person-circle
      - text: "Moodle"
        href: https://moodle.hdm-stuttgart.de/login/index.php
        aria-label: Moodle    
#    background: "#325b74"    


  sidebar:
#    background: "#325b74"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/myplaceholder
        text: "GitHub organization"
      - icon: person-fill
        text: "Moodle"
        href: https://moodle.hdm-stuttgart.de/login/index.php

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-syllabus.qmd
            text: Syllabus
          - href: index.qmd
            text: Schedule

      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources
          - href: project-tips-resources.qmd
            text: Tips + resources

      - section: "Konzept"
        contents:
          - href: docs/business-model-canvas.qmd
            text: Business Model Canvas
          - href: docs/value-proposition.qmd
            text: Value Proposition Canvas
          - href: docs/jobs-to-be-done.qmd
            text: Jobs to be Done
          - href: docs/user-persona.qmd
            text: User Persona


format:
  html:
    toc: true
    theme:
      light: [cosmo, style/course.scss]
      dark: [cosmo, style/course.scss, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap