project:
  type: website

execute:
  freeze: auto

website:
  page-navigation: true
  title: "Generative KI in der Bildung"
  description: "Webseite für den Kurs Generative KI in der Bildung an HdM Stuttgart, WS 24/25."
  site-url: "https://generative-ai-education.github.io/website/"
  repo-url: https://github.com/generative-ai-education/website
  repo-actions: [edit, issue]
  open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay  
  page-footer:
    left: |
      © [Jan Kirenz](https://www.kirenz.com/), 2024
    center:
      - text: "Willkommen"
        href: index.qmd
      - text: "Syllabus"
        href: kurs-syllabus.qmd  
    right:
      - icon: person-circle
      - text: "Moodle"
        href: https://moodle.hdm-stuttgart.de/course/view.php?id=20559
        aria-label: Moodle    
#    background: "#325b74"    


  sidebar:
#    background: "#325b74"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: person-fill
        text: "Moodle"
        href: https://moodle.hdm-stuttgart.de/course/view.php?id=20559

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Kurs-Hinweise"
        contents:
          - href: index.qmd
            text: Willkommen
          - href: kurs-syllabus.qmd
            text: Syllabus
          - href: projekt-ressourcen.qmd
            text: Ressourcen            

      - section: "Projektkonzept"
        contents:
          - href: docs/business-model-canvas.qmd
            text: Business Model Canvas
          - href: docs/value-proposition.qmd
            text: Value Proposition Canvas
          - href: docs/jobs-to-be-done.qmd
            text: Jobs to be Done
          - href: docs/user-persona.qmd
            text: User Persona


format:
  html:
    toc: true
    theme: cosmo
    css: theme.scss
    code-copy: true
    highlight-style: github-dark
    code-overflow: wrap
    author-meta: "Jan Kirenz"
    callout-appearance: simple