---
title: "Syllabus"
---

## Kursinformationen

|           | Tag       | Zeit              | Ort      |
|-----------|-----------|-------------------|----------|
| Vorlesung | Mittwoch  | 10:00 - 12:15 Uhr | [i118](https://horst.hdm-stuttgart.de/i118) |

## Lernziele

Dieser Kurs untersucht das transformative Potenzial der generativen künstlichen Intelligenz (KI) in den Bereichen Lehren und Lernen. Die Studierenden setzen sich mit den neuesten Fortschritten der generativen KI-Technologien auseinander, um deren Anwendungen bei der Automatisierung von Inhaltserstellung, der Personalisierung von Lernmaterialien und der Förderung interaktiver und adaptiver Lernumgebungen zu verstehen. 

Am Ende dieses Kurses werden die Studierenden in der Lage sein:

- Die grundlegenden Prinzipien der generativen KI und ihre Relevanz für die Bildung zu verstehen.
- Die potenziellen Auswirkungen der generativen KI auf traditionelle Lehr- und Lernparadigmen kritisch zu analysieren.
- Innovative Bildungswerkzeuge und -ansätze unter Verwendung generativer KI zu entwerfen und zu prototypisieren.

## Kursbewertung

### Überblick

| Bewertungskriterien                                   | Punkte |
|-------------------------------------------------------|--------|
| **1. Projektkonzept**                                  | **35** |
| Recherche                                              | 05     |
| BMC, JTBD & VPC, User Persona                          | 15     |
| IDEO Design Kit                                        | 15     |
| **2. Mock-up und Prototyping**                          | **50** |
| Genauigkeit und Funktionalität der Mock-ups            | 15     |
| Prototyp-Entwicklung inklusive Prompting               | 20     |
| Innovation und Kreativität                             | 15     |
| **3. Präsentation**                                     | **15** |
| Klarheit und Organisation                              | 05      |
| Bezug zu geeigneten Methoden                           | 05      |
| Visuelle und technische Qualität                       | 05      |
| **Gesamt**                                              | **100** |

### Projektkonzept 

*Für diese Aufgabe benötigen Sie [Miro](https://miro.com/de/) (ein Account wird bereitgestellt).*

1. Durchführung einer umfangreichen Recherche (klare Identifikation und Artikulation des Bildungsproblems oder der Chance, die sich mit Hilfe von KI ergibt). Auf Grundlage der gründlichen Recherche zu Benutzerbedürfnissen und relevantem Kontext (bsow. wie KI eingesetzt werden könnte) kann Aufgabe 2 bearbeitet werden.

2. Machen Sie sich zunächst mit dem [Business Model Canvas (BMC)](/docs/business-model-canvas.qmd) vertraut. Darauf aufbauend kann die Thematik [Value Proposition Canvas (VPC)](/docs/value-proposition.qmd) in Verbindung mit dem [Jobs to be Done (JTBD)](/docs/jobs-to-be-done.qmd) Ansatz bearbeitet werden. Auf Grundlage dieser Ansätze kann eine [User Persona](/docs/user-persona.qmd) abgeleitet werden. Im Rahmen dieser Aufgabe sollen die folgenden Inhalte in Miro erstellt werden:

  - [Customer Value Proposition Map](https://miro.com/miroverse/customer-value-proposition-map/)
  - [Business Model Canvas](https://miro.com/de/templates/business-model-canvas/)
  - [User-Persona](https://miro.com/templates/personas/)

3. Verwenden Sie die in Aufgabe 2 erarbeiteten Inhalte um [diese Vorlage](https://docs.google.com/document/d/1JK1IIW0h1MR4P9Z-29VpWISRz62Y7rA1cz8AQDTTqgs/edit?usp=sharing) unter Nutzung des [IDEO Design-Kits](https://www.designkit.org/resources/1.html) auszufüllen. Folgende Inhalte müssen bearbeitet werden:

  - Frame Your Design Challenge (p. 33).
  - Priorities topics: Card sort (p. 57).
  - Create Insight Statements (p. 83).
  - Create How Might We Questions (p. 87).
  - Create Frameworks (p. 90-93).
  - Create a Storyboard (114).

### Mock-up und Prototyping

*Für diese Aufgabe benötigen Sie einen Account bei Figma: Erstellen Sie einen [Figma-Account für Studierende](https://help.figma.com/hc/de/articles/360041061214-Bildungsstatus-verifizieren); Wählen Sie bei school's name: **Fachhochschule Stuttgart, Hochschule der Medien**.*

Erstellen Sie gemäß der Erkenntnisse aus dem Projektkonzept mit Hilfe von Figma Wireframes und Mock-Ups:

1. Erstellung eines Mock-Ups in Figma
2. Erstellung eines Prototyps in Figma und Entwicklung von geeigneten Prompts

Tutorials: [Figma for Beginners](https://help.figma.com/hc/en-us/sections/23691657321239-Courses); [Einführung in Prototyping mit Figma](https://help.figma.com/hc/de/articles/360040314193-Einf%C3%BChrung-in-Prototyping-in-Figma).


**Genauigkeit und Funktionalität der Mock-ups:** 

- Klarheit, Detail und Realismus der Figma-Mock-ups.
- Mock-ups sollten das Aussehen und die Funktionsweise der vorgeschlagenen Lösung genau darstellen.

**Prototyp-Entwicklung:** 

- Funktionalität, Benutzerfreundlichkeit und Übereinstimmung des Prototyps mit den Mock-up-Designs.
- Bewertung der Fähigkeit des Prototyps, das identifizierte Problem effektiv anzugehen.

- **Innovation und Kreativität:** 

- Originalität der Lösung und kreative Nutzung der Technologie im Prototyp.
- Das Potenzial der Lösung, die angestrebte Bildungsherausforderung zu bewältigen.

### Präsentation

**Klarheit und Organisation:** 

- Die Präsentation ist gut strukturiert, mit klaren Zielen, Ergebnissen und Schlussfolgerungen.
- Effektive Kommunikation des Wertes und der Auswirkungen des Projekts.

**Bezug zu geeigneten Methoden:** 

- Die in dem Projekt behandelten Methoden wurden sinnvoll in der Präsentation behandelt.

- **Visuelle und technische Qualität:** 

- Verwendung von Visualisierungen, Demonstrationen und/oder Multimedia zur Verbesserung der Präsentationseffektivität.
- Technische Gewandtheit bei der Vorstellung des Prototyps.

### Zusätzliche Richtlinien:

- **Zusammenarbeit:** Die Studierenden werden ermutigt, in Teams zu arbeiten, aber individuelle Beiträge müssen klar definiert sein.
- **Ethische Überlegungen:** Projekte müssen ethische Standards einhalten, insbesondere bei der Verwendung von Daten und der Berücksichtigung von Privatsphäre und Zugänglichkeit.
- **Fortschrittsupdates:** Regelmäßige Check-ins oder Fortschrittsberichte werden empfohlen, um sicherzustellen, dass die Projekte auf Kurs bleiben und mit den Kurszielen übereinstimmen.

## Benotung

Die Endnote wird auf Basis der folgenden Schwellenwerte bestimmt:

| Note | Punkte |
|------|--------|
| 1,0  | 96 - 100 |
| 1,3  | 91 - 95  |
| 1,7  | 85 - 90  |
| 2,0  | 80 - 84  |
| 2,3  | 75 - 79  |
| 2,7  | 70 - 74  |
| 3,0  | 65 - 69  |
| 3,3  | 60 - 64  |
| 3,7  | 55 - 59  |
| 4,0  | 50 - 54  |
| 4,7  | 15 - 49  |
| 5,0  | 0 - 14   |

## Richtlinie für verspätete Abgaben

Die Abgabefristen für Aufgaben sind dazu da, Ihnen zu helfen, mit dem Kursmaterial Schritt zu halten. Ich verstehe jedoch, dass gelegentlich Dinge vorkommen können, die es schwierig machen, eine Aufgabe fristgerecht einzureichen. Hier sind die Regeln für verspätete Einreichungen:

- Projektaufgaben können bis zu 2 Tage zu spät eingereicht werden. Für jeden 24-Stunden-Zeitraum, in dem die Projektaufgabe zu spät ist, gibt es einen Abzug von 25%.

Wenn wichtige Umstände Sie daran hindern, eine Labor- oder Hausaufgabe bis zum angegebenen Abgabetermin abzuschließen, können Sie mir vor der Frist eine E-Mail an [kirenz@hdm-stuttgart.de](mailto:kirenz@hdm-stuttgart.de) senden.


## Wo Sie Hilfe bekommen

- Wenn Sie während der Vorlesung eine Frage haben, zögern Sie nicht, sie zu stellen!
- Außerhalb des Unterrichts sollten allgemeine Fragen zu Kursinhalten oder Aufgaben im Moodle-Kursforum gepostet werden.
- E-Mails sollten für Fragen reserviert sein, die nicht für das öffentliche Forum geeignet sind. **Wenn Sie mir eine E-Mail schicken, fügen Sie bitte den Namen unseres Kurses in die Betreffzeile ein.**

Schauen Sie sich die [Support](course-support.qmd)-Seite für weitere Ressourcen an.